const verifyOTP = require("./verify");

const secretKey = 'EFICSZSBOI4FESTVPB2FMXSGIIXCYUDW'; // Use the generated secret
console.log("Secret Key:", secretKey);

const userOTP = "522101"; // Replace with the OTP generated by the Authenticator app

const verificationResult = verifyOTP(secretKey, userOTP);

if (verificationResult) {
    console.log("OTP verification successful!");
} else {
    console.log("OTP verification failed!");
}
